package InternetBakingApp;


/**
* InternetBakingApp/_InternetBakingStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from InternetBakingApp.idl
* Sunday, 11 September 2022 23:15:06 o'clock CEST
*/

public class _InternetBakingStub extends org.omg.CORBA.portable.ObjectImpl implements InternetBakingApp.InternetBaking
{

  public boolean autenticar (String usuario, String senha)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("autenticar", true);
                $out.write_string (usuario);
                $out.write_string (senha);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return autenticar (usuario, senha        );
            } finally {
                _releaseReply ($in);
            }
  } // autenticar

  public double cosultarSaldo (String numeroConta)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("cosultarSaldo", true);
                $out.write_string (numeroConta);
                $in = _invoke ($out);
                double $result = $in.read_double ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return cosultarSaldo (numeroConta        );
            } finally {
                _releaseReply ($in);
            }
  } // cosultarSaldo

  public boolean pagarServico (String entidade, String referencia)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("pagarServico", true);
                $out.write_string (entidade);
                $out.write_string (referencia);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return pagarServico (entidade, referencia        );
            } finally {
                _releaseReply ($in);
            }
  } // pagarServico

  public boolean transferencia (String numeroContaBenificiaria, double montante)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("transferencia", true);
                $out.write_string (numeroContaBenificiaria);
                $out.write_double (montante);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return transferencia (numeroContaBenificiaria, montante        );
            } finally {
                _releaseReply ($in);
            }
  } // transferencia

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:InternetBakingApp/InternetBaking:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _InternetBakingStub
