package InternetBakingApp;


/**
* InternetBakingApp/InternetBakingOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from InternetBakingApp.idl
* Sunday, 11 September 2022 23:15:06 o'clock CEST
*/

public interface InternetBakingOperations 
{
  boolean autenticar (String usuario, String senha);
  double cosultarSaldo (String numeroConta);
  boolean pagarServico (String entidade, String referencia);
  boolean transferencia (String numeroContaBenificiaria, double montante);
} // interface InternetBakingOperations
