package InternetBakingApp;


/**
* InternetBakingApp/InternetBaking.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from InternetBakingApp.idl
* Sunday, 11 September 2022 23:15:06 o'clock CEST
*/

public interface InternetBaking extends InternetBakingOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface InternetBaking
