package InternetBakingApp;


/**
* InternetBakingApp/InternetBakingPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from InternetBakingApp.idl
* Sunday, 11 September 2022 23:15:06 o'clock CEST
*/

public abstract class InternetBakingPOA extends org.omg.PortableServer.Servant
 implements InternetBakingApp.InternetBakingOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("autenticar", new java.lang.Integer (0));
    _methods.put ("cosultarSaldo", new java.lang.Integer (1));
    _methods.put ("pagarServico", new java.lang.Integer (2));
    _methods.put ("transferencia", new java.lang.Integer (3));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // InternetBakingApp/InternetBaking/autenticar
       {
         String usuario = in.read_string ();
         String senha = in.read_string ();
         boolean $result = false;
         $result = this.autenticar (usuario, senha);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 1:  // InternetBakingApp/InternetBaking/cosultarSaldo
       {
         String numeroConta = in.read_string ();
         double $result = (double)0;
         $result = this.cosultarSaldo (numeroConta);
         out = $rh.createReply();
         out.write_double ($result);
         break;
       }

       case 2:  // InternetBakingApp/InternetBaking/pagarServico
       {
         String entidade = in.read_string ();
         String referencia = in.read_string ();
         boolean $result = false;
         $result = this.pagarServico (entidade, referencia);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 3:  // InternetBakingApp/InternetBaking/transferencia
       {
         String numeroContaBenificiaria = in.read_string ();
         double montante = in.read_double ();
         boolean $result = false;
         $result = this.transferencia (numeroContaBenificiaria, montante);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:InternetBakingApp/InternetBaking:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public InternetBaking _this() 
  {
    return InternetBakingHelper.narrow(
    super._this_object());
  }

  public InternetBaking _this(org.omg.CORBA.ORB orb) 
  {
    return InternetBakingHelper.narrow(
    super._this_object(orb));
  }


} // class InternetBakingPOA
