package InternetBakingApp;

/**
* InternetBakingApp/InternetBakingHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from InternetBakingApp.idl
* Sunday, 11 September 2022 23:15:06 o'clock CEST
*/

public final class InternetBakingHolder implements org.omg.CORBA.portable.Streamable
{
  public InternetBakingApp.InternetBaking value = null;

  public InternetBakingHolder ()
  {
  }

  public InternetBakingHolder (InternetBakingApp.InternetBaking initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = InternetBakingApp.InternetBakingHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    InternetBakingApp.InternetBakingHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return InternetBakingApp.InternetBakingHelper.type ();
  }

}
